// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// xdist
arma::mat xdist(arma::mat X, arma::vec mean0, arma::mat GPsigma, arma::vec addmean, float sdobs, std::string maxmin, int K);
RcppExport SEXP _ESMultiTask_xdist(SEXP XSEXP, SEXP mean0SEXP, SEXP GPsigmaSEXP, SEXP addmeanSEXP, SEXP sdobsSEXP, SEXP maxminSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mean0(mean0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type GPsigma(GPsigmaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type addmean(addmeanSEXP);
    Rcpp::traits::input_parameter< float >::type sdobs(sdobsSEXP);
    Rcpp::traits::input_parameter< std::string >::type maxmin(maxminSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(xdist(X, mean0, GPsigma, addmean, sdobs, maxmin, K));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ESMultiTask_xdist", (DL_FUNC) &_ESMultiTask_xdist, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_ESMultiTask(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
