# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

xdist <- function(X, mean0, GPsigma, addmean, sdobs, maxmin = "both", K = 1000L) {
    .Call(`_ESMultiTask_xdist`, X, mean0, GPsigma, addmean, sdobs, maxmin, K)
}

